DormWebApplication/DormWebApplication/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DormWebApplication
{
    public partial class Room
    {
        public Room()
        {
            Furnitures = new HashSet<Furniture>();
            Inhabitants = new HashSet<Inhabitant>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Поле не повинно бути порожнім")]
        [Range(1, 100, ErrorMessage ="Кількість мешканців має бути в межах від 1 до 100")]
        [Display(Name = "К-сть місць")]
        public int CountPlace { get; set; }

        [Required(ErrorMessage = "Поле не повинно бути порожнім")]
        [Display(Name = "Поверх")]
        public int FloorNumber { get; set; }

        [Display(Name = "Мешканці")]
        public string? Resident { get; set; }

        [Required(ErrorMessage = "Поле не повинно бути порожнім")]
        [Display(Name = "Номер кімнати")]
        public string RoomNumber { get; set; } = null!;

        [Display(Name ="Поверх")]
        public virtual Floor Floor { get; set; } = null!;

        public virtual ICollection<Furniture> Furnitures { get; set; }

        public virtual ICollection<Inhabitant> Inhabitants { get; set; }
    }
}

DormWebApplication/DormWebApplication/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DormWebApplication;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Authorization;

namespace DormWebApplication.Controllers
{
    [Authorize(Roles ="admin, user")]
    public class RoomsController : Controller
    {
        private readonly DBDormContext _context;

        public RoomsController(DBDormContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            var dBDormContext = _context.Rooms.Include(r => r.Floor);
            return View(await dBDormContext.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Floor)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (room == null)
            {
                return NotFound();
            }

            var students = _context.Inhabitants.Where(s => s.RoomId == id);
            ViewBag.Students = students;

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "FloorNumber");
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CountPlace,FloorNumber,Resident,RoomNumber")] Room room)
        {
            if (ModelState.IsValid)
            {
                var isRoom = _context.Rooms.Where(r=> r.RoomNumber == room.RoomNumber).Where(i=>i.CountPlace == room.CountPlace);
                var floor = _context.Floors.Where(f => f.Id == room.FloorNumber).FirstOrDefault();
                var floorRoom = room.RoomNumber[0].ToString();
                //var placeRoom = room.CountPlace.ToString();

                if(isRoom != null)
                {
                    if (isRoom.Count() == 0)
                    {
                        if (floorRoom == floor.FloorNumber.ToString())
                        {
                            _context.Add(room);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));
                        }
                        else
                        {
                            await _context.SaveChangesAsync();
                            ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "Id", room.FloorNumber);
                            return View(room);
                        }
                    }
                    else
                    {
                        
                        await _context.SaveChangesAsync();
                        ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "Id", room.FloorNumber);
                        return View(room);
                    }
                }


            }
            ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "Id", room.FloorNumber);
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "FloorNumber", room.FloorNumber);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CountPlace,FloorNumber,Resident,RoomNumber")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FloorNumber"] = new SelectList(_context.Floors, "Id", "Id", room.FloorNumber);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Floor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            var inhabs = _context.Inhabitants.Where(i => i.RoomId == room.Id).ToList();
            var furnts = _context.Furnitures.Where(f => f.RoomId == room.Id).ToList();

            if (furnts != null)
            {
                if (furnts.Count() != 0)
                {
                    foreach (var fur in furnts)
                    {
                        fur.RoomId = null;
                        _context.SaveChanges();
                    }
                }
            }

            if (inhabs!=null)
            {
                if (inhabs.Count() != 0)
                {
                    foreach (var inh in inhabs)
                    {
                        _context.Remove(inh);
                    }
                }
            }

            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                var worksheetRoomName = worksheet.Name[0].ToString() + worksheet.Name[1].ToString() + worksheet.Name[2].ToString();
                                Room newRoom;

                                var r = (from room in _context.Rooms
                                         where room.RoomNumber.Contains(worksheetRoomName)
                                         select room).ToList();

                                if (r.Count > 0)
                                {
                                    newRoom = r[0];
                                }
                                else
                                {
                                    newRoom = new Room();
                                    newRoom.RoomNumber = worksheet.Name;

                                    var floor = worksheet.Cell("B2").Value;
                                    //Чи існує поверх
                                    var isFloorEmpty = (from fl in _context.Floors
                                                        where fl.FloorNumber == Convert.ToInt32(floor)
                                                        select fl).FirstOrDefault();
                                    Floor newFloor;

                                    if (isFloorEmpty == null)
                                    {
                                        newFloor = new Floor();
                                        newFloor.FloorNumber = Convert.ToInt32(floor);
                                        if (worksheet.Cell("B3").Value is (object)"TRUE" or (object)"ИСТИНА" or (object)"ІСТИНА")
                                        {
                                            newFloor.IsKitchenOpen = true;
                                        }
                                        else
                                            newFloor.IsKitchenOpen = false;

                                        _context.Floors.Add(newFloor);
                                    }
                                    else

DormWebApplication/DormWebApplication/Views/Rooms/Create.cshtml
@model DormWebApplication.Room

@{
    ViewData["Title"] = "Create";
}

<h1>Створити</h1>

<h4 id="id">Кімната №</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CountPlace" class="control-label"></label>
                <input asp-for="CountPlace" class="form-control" />
                <span asp-validation-for="CountPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FloorNumber" class="control-label"></label>
                <select asp-for="FloorNumber" class ="form-control" asp-items="ViewBag.FloorNumber"></select>
            </div>
            <div class="form-group">
                <label asp-for="Resident" class="control-label"></label>
                <input asp-for="Resident" class="form-control" />
                <span asp-validation-for="Resident" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" onchange="func()" id="name"/>
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function func(){
        let name = document.getElementById("name").value;
        document.getElementById("id").innerHTML = "Кімната №" + name;
    }
</script>

DormWebApplication/DormWebApplication/Views/Rooms/Delete.cshtml
@model DormWebApplication.Room

@{
    ViewData["Title"] = "Delete";
}

<h3>Видалити</h3>

<h3>Ви справді бажаєте видалити цю кімнату?</h3>
<div>
    <h4>Кімната @Model.RoomNumber</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountPlace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resident)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resident)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

DormWebApplication/DormWebApplication/Views/Rooms/Details.cshtml
@model DormWebApplication.Room

@{
    ViewData["Title"] = "Details";
}

<h3>Детальна інформація</h3>

<div>
    <h4>Кімната @Model.RoomNumber</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountPlace)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resident)
        </dt>
        <dd class = "col-sm-10">
            @{
                foreach(var stud in ViewBag.Students)
                {                
                    @stud.Name 
                    <br />
                }
            }   
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor.Id)
        </dd>
    </dl>
</div>

@if(User.Identity.IsAuthenticated && User.IsInRole("user"))
{
    <div>
    <a asp-action="Index">Назад</a>
    </div>
}
else
{
    <div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Змінити</a> |
    <a asp-action="Index">Назад</a>
</div>
}

DormWebApplication/DormWebApplication/Views/Rooms/Edit.cshtml
@model DormWebApplication.Room

@{
    ViewData["Title"] = "Edit";
}

<h3>Зміна інформації</h3>

<h4>Кімната</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CountPlace" class="control-label"></label>
                <input asp-for="CountPlace" class="form-control" />
                <span asp-validation-for="CountPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FloorNumber" class="control-label"></label>
                <select asp-for="FloorNumber" class="form-control" asp-items="ViewBag.FloorNumber"></select>
                <span asp-validation-for="FloorNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resident" class="control-label"></label>
                <input asp-for="Resident" class="form-control" />
                <span asp-validation-for="Resident" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DormWebApplication/DormWebApplication/Views/Rooms/Index.cshtml
@model IEnumerable<DormWebApplication.Room>

@{
    ViewData["Title"] = "Index";
}

<h3>Кімнати</h3>
@if(User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
   <p>
    <a asp-action="Create">Створити нову</a>
    </p> 
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Floor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(User.Identity.IsAuthenticated && User.IsInRole("user"))
        {
            @foreach (var item in Model) 
            {
        <tr>
@{
                    string number = $"{item.RoomNumber}/{item.CountPlace}";
                }
            <td>           
                @number
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor.FloorNumber)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a>
            </td>
        </tr>
            }
        }
        else
        {
            @foreach (var item in Model)
            {
                <tr>
                @{
                    string number = $"{item.RoomNumber}/{item.CountPlace}";
                }
            <td>           
                @number
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor.FloorNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Змінити</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
            </td>
            </tr>
            }
        }
    </tbody>
</table>

@if(User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
<br />

<div>
    <h3>Оберіть excel-файл для завантаження</h3>
    @using (Html.BeginForm("Import", "Rooms", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div >
            <div>Завантажте Excel-файл:</div>
                <div>
                    <input type="file" name="fileExcel" id="fileExcel"/>
                </div>
                <div class="dropdown-divider"></div>
                    <div>Підтвердити:</div>
                <div>
                    <input type="submit" value="Імпорт" /> 
                </div>
                <div class="dropdown-divider"></div>   
                   <div>
                        <h6>Завантаження інформації в файл</h6>
                        <div class="form-group">
                            <input asp-action="Export" type="submit" value="Експорт в Excel" class="btn btn-success" />
                        </div>
                        <div class="form-group">
                            <input asp-action="DExport" type="submit" value="Експорт в Docs" class="btn btn-primary" />
                        </div>
                   </div>
            </div>
    }
</div>
}